spring.application.name=webapp-backend
spring.datasource.url=jdbc:postgresql://dpg-d7uqdj1o3t8c73fs53og-a.singapore-postgres.render.com:5432/signup_x04y
spring.datasource.username=mentedge_user
spring.datasource.password=luB2zJ4ERdTPjJVbFWFK0qJ952JpS8e5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


